# NumPy : numerical Python
<pre><b>Numpy is a Python library which is use to perform different mathamatical operations on arrays.
Array is denoted with '[ ]'.It is ordered(index position is fixed),mutable(items can be modified) and homogeneous(items of similar datatypes) collection of items.</pre>

In [1]:
import numpy as np

In [3]:
#Creating 1-D Array
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [4]:
type(a)  #ndarray : n-dimensional array

numpy.ndarray

In [5]:
#list to array
a = np.array([20,2.5,'cat',50,True])
a

array(['20', '2.5', 'cat', '50', 'True'], dtype='<U32')

In [6]:
#tuple to array
t = np.array((10,20,30,40))
t

array([10, 20, 30, 40])

In [7]:
#set to array
s = np.array({20,20,20,45,45,67,89,89})
s

array({89, 67, 20, 45}, dtype=object)

In [8]:
#dictionary to array
d = np.array({'a':1,'b':2,'c':3})
d

array({'a': 1, 'b': 2, 'c': 3}, dtype=object)

In [9]:
#Create 2-D array
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
a = np.array([(1,2,3),(4,5,6)])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
b = np.array([[1,2,3,4],[5,6,7,8],[4,0,9,4]])
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [4, 0, 9, 4]])

In [21]:
#Array Attributes
b.shape #to check the shape of array

(3, 4)

In [23]:
b.size #to check total number of elements

12

In [25]:
b.ndim #to check number of dimension of a matrix

2

In [27]:
#arange : it returns a 1-D array of given sequence
np.arange(1,11,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [33]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [35]:
np.zeros((4,4),dtype='int')

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [37]:
np.zeros((4,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [41]:
np.zeros((4,4)).astype(int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [43]:
np.ones(4)

array([1., 1., 1., 1.])

In [45]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [47]:
#full
np.full((5,5),8)

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [49]:
np.full((5,5),'cat')

array([['cat', 'cat', 'cat', 'cat', 'cat'],
       ['cat', 'cat', 'cat', 'cat', 'cat'],
       ['cat', 'cat', 'cat', 'cat', 'cat'],
       ['cat', 'cat', 'cat', 'cat', 'cat'],
       ['cat', 'cat', 'cat', 'cat', 'cat']], dtype='<U3')

In [51]:
#eye
np.eye(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [57]:
#linspace - equally distributed numbers
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [59]:
np.linspace(1,100)

array([  1.        ,   3.02040816,   5.04081633,   7.06122449,
         9.08163265,  11.10204082,  13.12244898,  15.14285714,
        17.16326531,  19.18367347,  21.20408163,  23.2244898 ,
        25.24489796,  27.26530612,  29.28571429,  31.30612245,
        33.32653061,  35.34693878,  37.36734694,  39.3877551 ,
        41.40816327,  43.42857143,  45.44897959,  47.46938776,
        49.48979592,  51.51020408,  53.53061224,  55.55102041,
        57.57142857,  59.59183673,  61.6122449 ,  63.63265306,
        65.65306122,  67.67346939,  69.69387755,  71.71428571,
        73.73469388,  75.75510204,  77.7755102 ,  79.79591837,
        81.81632653,  83.83673469,  85.85714286,  87.87755102,
        89.89795918,  91.91836735,  93.93877551,  95.95918367,
        97.97959184, 100.        ])

In [61]:
#Random Numbers
np.random.rand()

0.46471048644062984

In [63]:
np.random.rand(5)

array([0.18466161, 0.52628811, 0.22148187, 0.02042734, 0.47633217])

In [65]:
np.random.rand(3,4)

array([[0.66534087, 0.89868807, 0.72336042, 0.84030904],
       [0.15477888, 0.96557729, 0.620168  , 0.10389667],
       [0.01493992, 0.29413207, 0.64758778, 0.05432841]])

In [67]:
np.random.rand(3,4)+100

array([[100.0712321 , 100.9110309 , 100.05370412, 100.34702287],
       [100.78139379, 100.97505405, 100.79364352, 100.29855258],
       [100.21716112, 100.65622952, 100.20534545, 100.14862284]])

In [69]:
np.random.rand(3,4)*100

array([[18.62918196, 34.14943429, 86.85694004, 83.03935511],
       [34.73504468,  2.16881124, 74.29641436, 66.53991153],
       [88.58894834, 46.12715215, 75.27588237, 22.21654173]])

In [71]:
np.random.randint(1,20)

2

In [73]:
np.random.randint(1,20,(5,5))

array([[19,  9,  4,  2, 15],
       [ 4, 18,  6, 11, 12],
       [ 2, 16,  2,  1, 14],
       [16,  3, 16, 16, 18],
       [ 8, 13, 13,  6, 18]], dtype=int32)

In [131]:
#Mathamatical functions
a = np.array([21,35,74,85,50])
b = np.array([2,7,8,9,5])

print(a)
print(b)

[21 35 74 85 50]
[2 7 8 9 5]


In [77]:
np.add(a,b)

array([23, 42, 82, 94, 55])

In [81]:
np.subtract(a,b)

array([19, 28, 66, 76, 45])

In [83]:
np.multiply(a,b)

array([ 42, 245, 592, 765, 250])

In [85]:
np.divide(a,b)

array([10.5       ,  5.        ,  9.25      ,  9.44444444, 10.        ])

In [89]:
np.floor_divide(a,b)

array([10,  5,  9,  9, 10])

In [91]:
np.mod(a,b)

array([1, 0, 2, 4, 0])

In [93]:
np.divmod(a,b)

(array([10,  5,  9,  9, 10]), array([1, 0, 2, 4, 0]))

In [105]:
np.sqrt(a)

array([4.58257569, 5.91607978, 8.60232527, 9.21954446, 7.07106781])

In [101]:
np.power(b,2)

array([ 4, 49, 64, 81, 25])

In [107]:
np.log(a)

array([3.04452244, 3.55534806, 4.30406509, 4.44265126, 3.91202301])

In [109]:
np.log(b)

array([0.69314718, 1.94591015, 2.07944154, 2.19722458, 1.60943791])

In [111]:
np.log10(a)

array([1.32221929, 1.54406804, 1.86923172, 1.92941893, 1.69897   ])

In [113]:
np.sin(a)

array([ 0.83665564, -0.42818267, -0.98514626, -0.17607562, -0.26237485])

In [115]:
np.cos(a)

array([-0.54772926, -0.90369221,  0.17171734, -0.98437664,  0.96496603])

In [117]:
np.tan(a)

array([-1.52749853,  0.47381472, -5.73702254,  0.17887017, -0.27190061])

In [119]:
#cot
1/np.tan(a)

array([-0.65466512,  2.11052962, -0.17430644,  5.59064704, -3.67781445])

In [143]:
#Statistical function
a

array([21, 35, 74, 85, 50])

In [145]:
np.max(a)

np.int64(85)

In [147]:
np.min(a)

np.int64(21)

In [149]:
#argmax
np.argmax(a)

np.int64(3)

In [151]:
#argmin
np.argmin(a)

np.int64(0)

In [153]:
np.median(a)

np.float64(50.0)

In [155]:
np.mean(a)

np.float64(53.0)

In [157]:
np.std(a)

np.float64(23.757104200638594)

In [159]:
#var - variance
np.var(a)

np.float64(564.4)

In [163]:
#cumsum - Cumulutive Summation
b

array([2, 7, 8, 9, 5])

In [165]:
np.cumsum(b)

array([ 2,  9, 17, 26, 31])

In [167]:
#cumprod - Cumulutive Product
np.cumprod(b)

array([   2,   14,  112, 1008, 5040])

In [175]:
np.cumulative_prod(b)

array([   2,   14,  112, 1008, 5040])

In [177]:
#repeat
a = np.array([1,2,3,4])
np.repeat(a,4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4])

In [181]:
#tile
a = np.array([1,2,3,4])
np.tile(a,4)

array([1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4])

In [183]:
#where
a = np.array([1,2,4,3,4,4,5,4,6,4])
np.where(a==4)

(array([2, 4, 5, 7, 9]),)

In [185]:
#Vector Maths
a = np.array([[1,3],[2,4]])
b = np.array([[5,7],[9,8]])

print(a)
print(b)

[[1 3]
 [2 4]]
[[5 7]
 [9 8]]


In [187]:
#dot product
np.dot(a,b)

array([[32, 31],
       [46, 46]])

In [189]:
#cross product
np.cross(a,b)

C:\Users\USER\AppData\Local\Temp\ipykernel_25276\1689352882.py:2: DeprecationWarning: Arrays of 2-dimensional vectors are deprecated. Use arrays of 3-dimensional vectors instead. (deprecated in NumPy 2.0)
  np.cross(a,b)


array([ -8, -20])

In [191]:
#Transpose
np.transpose(a)

array([[1, 2],
       [3, 4]])

In [193]:
a.T

array([[1, 2],
       [3, 4]])

In [195]:
#Indexing and Slicing in 1-D array
a = np.array([34,67,89,34,56,90,38])
a

array([34, 67, 89, 34, 56, 90, 38])

In [197]:
#Indexing
a[3]

np.int64(34)

In [199]:
a[-2]

np.int64(90)

In [201]:
#Slicing
a[1:7:2]

array([67, 34, 90])

In [211]:
a[-6::2]

array([67, 34, 90])

In [213]:
a[-6:-1:2]

array([67, 34, 90])

In [205]:
a[::]

array([34, 67, 89, 34, 56, 90, 38])

In [207]:
a[::-1]

array([38, 90, 56, 34, 89, 67, 34])

In [215]:
#Indexing and Slicing in 2-D array
b = np.random.randint(1,20,(5,5))
b

array([[ 1, 16,  4, 12,  7],
       [ 8,  6,  2,  7, 16],
       [ 8, 17,  7, 18, 12],
       [ 8, 11, 10, 14, 18],
       [ 1,  9, 13, 12, 13]], dtype=int32)

In [217]:
#Indexing
#Syntax : var[row_index,col_index]
b[1,3]

np.int32(7)

In [219]:
b[3]  #Bydefault row

array([ 8, 11, 10, 14, 18], dtype=int32)

In [221]:
#Slicing in 2-D array
#row_slicing = var[strt index : end index+1 : stop]
#column_slicing = var[strt index : end index+1 : stop]
b[1:4:1,1:4:1]

array([[ 6,  2,  7],
       [17,  7, 18],
       [11, 10, 14]], dtype=int32)

In [223]:
#all rows and even columns(0,2,4)
b[0:5:1,0:5:2]

array([[ 1,  4,  7],
       [ 8,  2, 16],
       [ 8,  7, 12],
       [ 8, 10, 18],
       [ 1, 13, 13]], dtype=int32)

In [227]:
b[::1,::2]

array([[ 1,  4,  7],
       [ 8,  2, 16],
       [ 8,  7, 12],
       [ 8, 10, 18],
       [ 1, 13, 13]], dtype=int32)

In [225]:
#odd rows and odd columns
b[1:5:2,1:5:2]

array([[ 6,  7],
       [11, 14]], dtype=int32)

In [231]:
b[1::2,1::2]

array([[ 6,  7],
       [11, 14]], dtype=int32)

In [245]:
#Concatenation : joining the matrix
a = np.random.randint(1,10,(2,2))
a

array([[7, 1],
       [6, 3]], dtype=int32)

In [253]:
b = np.random.randint(1,20,(2,4))
b

array([[ 3, 13, 14,  6],
       [14,  2, 13, 19]], dtype=int32)

In [255]:
c = np.random.randint(1,20,(4,4))
c

array([[ 1,  6, 19,  6],
       [ 1, 17, 16, 14],
       [16,  9, 16,  3],
       [15, 16, 15, 13]], dtype=int32)

In [257]:
np.concatenate((a,b),axis=1) #axis=1(column wise)

array([[ 7,  1,  3, 13, 14,  6],
       [ 6,  3, 14,  2, 13, 19]], dtype=int32)

In [259]:
np.concatenate((b,c),axis=0) #axis=0(row wise)

array([[ 3, 13, 14,  6],
       [14,  2, 13, 19],
       [ 1,  6, 19,  6],
       [ 1, 17, 16, 14],
       [16,  9, 16,  3],
       [15, 16, 15, 13]], dtype=int32)

In [265]:
#Stack
np.hstack((a,b)) #hstack : horizontal stack

array([[ 7,  1,  3, 13, 14,  6],
       [ 6,  3, 14,  2, 13, 19]], dtype=int32)

In [267]:
np.vstack((b,c)) #vstack : vertical stack

array([[ 3, 13, 14,  6],
       [14,  2, 13, 19],
       [ 1,  6, 19,  6],
       [ 1, 17, 16, 14],
       [16,  9, 16,  3],
       [15, 16, 15, 13]], dtype=int32)

In [269]:
#Diagonal
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [271]:
np.diagonal(a)

array([1, 5, 9])

In [273]:
np.flip(a)

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [275]:
np.flip(a,axis=1) #Horizonatlly flip

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [277]:
np.flip(a,axis=0) #vertically flip

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [279]:
np.diagonal(np.flip(a,axis=1))

array([3, 5, 7])